name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          npm ci
          npm install --package-lock-only
      
      - name: Type check
        run: npm run type-check
      
      - name: Lint
        run: npm run lint
      
      - name: Validate Next.js config
        run: |
          if [ ! -f "next.config.js" ]; then
            echo "❌ next.config.js is missing"
            exit 1
          fi
          if ! grep -q "output: 'export'" next.config.js; then
            echo "❌ next.config.js must include 'output: export' for static export"
            exit 1
          fi
      
      - name: Validate package.json
        run: |
          if ! grep -q '"build": "next build"' package.json; then
            echo "❌ package.json must include 'build' script"
            exit 1
          fi
          if [ ! -f "package-lock.json" ]; then
            echo "❌ package-lock.json is missing"
            exit 1
          fi

  build:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Next.js
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d "out" ]; then
            echo "❌ Build failed: 'out' directory not found"
            exit 1
          fi
          if [ ! -f "out/index.html" ]; then
            echo "❌ Build failed: index.html not found in out directory"
            exit 1
          fi
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 